"""
Export SQL DDL schema for different database dialects.

Similar to `drizzle-kit export`, this generates CREATE TABLE statements
without connecting to an actual database.

Usage:
    python export_schema.py --dialect postgres
    python export_schema.py --dialect mysql
    python export_schema.py --dialect sqlite
    python export_schema.py --dialect postgres --output schema.sql
"""

import argparse
from datetime import date, datetime
from pathlib import Path
from types import NoneType, UnionType
from typing import Any, Union, get_args, get_origin
from uuid import UUID

from sqlalchemy.schema import CreateTable
from sqlalchemy.dialects import postgresql, mysql, sqlite

from sqlmodel import SQLModel

# Import all models to register them with SQLModel metadata
import models  # noqa: F401


# Dialect mapping
DIALECTS = {
    "postgres": postgresql.dialect(),
    "postgresql": postgresql.dialect(),
    "mysql": mysql.dialect(),
    "mariadb": mysql.dialect(),
    "sqlite": sqlite.dialect(),
}

TYPE_ALIAS_EXPORTS = {
    "Image": "TrialImage",
}


def get_create_table_sql(table, dialect) -> str:
    """Generate CREATE TABLE SQL for a single table."""
    return str(CreateTable(table).compile(dialect=dialect))


def _dedupe_preserving_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    unique_items: list[str] = []

    for item in items:
        if item not in seen:
            seen.add(item)
            unique_items.append(item)

    return unique_items


def _render_union_type(annotation: Any) -> str:
    member_types = []
    includes_null = False

    for member in get_args(annotation):
        if member is NoneType:
            includes_null = True
            continue

        member_types.append(_python_type_to_typescript(member))

    rendered_members = _dedupe_preserving_order(member_types)
    if includes_null:
        rendered_members.append("null")

    return " | ".join(rendered_members) or "null"


def _render_collection_type(annotation: Any) -> str:
    item_types = get_args(annotation)
    item_type = item_types[0] if item_types else Any
    return f"{_python_type_to_typescript(item_type)}[]"


def _render_scalar_type(annotation: Any) -> str | None:
    if annotation in (str, UUID, date, datetime):
        return "string"

    if annotation in (int, float):
        return "number"

    if annotation is bool:
        return "boolean"

    if annotation in (Any, object):
        return "unknown"

    if isinstance(annotation, type) and issubclass(annotation, SQLModel):
        return annotation.__name__

    return None


def _python_type_to_typescript(annotation: Any) -> str:
    origin = get_origin(annotation)

    if origin in (Union, UnionType):
        return _render_union_type(annotation)

    if origin in (list, set, tuple):
        return _render_collection_type(annotation)

    scalar_type = _render_scalar_type(annotation)
    return scalar_type or "unknown"


def _iter_model_properties(model: type[SQLModel]) -> list[tuple[str, Any]]:
    properties = [(name, field.annotation) for name, field in model.model_fields.items()]
    computed_fields = getattr(model, "model_computed_fields", {})

    for name, info in computed_fields.items():
        properties.append((name, info.return_type))

    return properties


def export_typescript_models() -> str:
    """Export TypeScript interfaces derived from the SQLModel schema definitions."""
    lines = [
        "// TechConnect generated TypeScript models",
        "// Generated by packages/schemas/export_schema.py",
        "// Do not edit directly.",
        "",
    ]

    for model_name in models.__all__:
        model = getattr(models, model_name)
        lines.append(f"export interface {model_name} {{")

        for property_name, annotation in _iter_model_properties(model):
            lines.append(f"  {property_name}: {_python_type_to_typescript(annotation)};")

        lines.append("}")
        lines.append("")

    for original_name, alias_name in TYPE_ALIAS_EXPORTS.items():
        lines.append(f"export type {alias_name} = {original_name};")

    return "\n".join(lines).rstrip() + "\n"


def export_schema(dialect_name: str) -> str:
    """
    Export the complete schema as SQL DDL statements.

    Args:
        dialect_name: Database dialect ('postgres', 'mysql', 'mariadb', 'sqlite')

    Returns:
        Complete SQL schema as a string
    """
    if dialect_name not in DIALECTS:
        raise ValueError(f"Unknown dialect: {dialect_name}. Choose from: {list(DIALECTS.keys())}")

    dialect = DIALECTS[dialect_name]

    # Get all tables in dependency order
    metadata = SQLModel.metadata

    # Generate header
    lines = [
        "-- TechConnect Database Schema",
        f"-- Dialect: {dialect_name}",
        "-- Generated by export_schema.py",
        "--",
        "-- This file was auto-generated from SQLModel definitions.",
        "-- Do not edit directly.",
        "",
    ]

    # Generate CREATE TABLE statements in correct order (respecting foreign keys)
    for table in metadata.sorted_tables:
        sql = get_create_table_sql(table, dialect)
        # Clean up and format
        sql = sql.strip()
        if not sql.endswith(";"):
            sql += ";"
        lines.append(sql)
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Export TechConnect schemas as SQL DDL or TypeScript models"
    )
    parser.add_argument(
        "--format",
        choices=["sql", "typescript"],
        default="sql",
        help="Output format (default: sql)",
    )
    parser.add_argument(
        "--dialect",
        "-d",
        choices=["postgres", "postgresql", "mysql", "mariadb", "sqlite"],
        default="postgres",
        help="Database dialect for SQL output (default: postgres)",
    )
    parser.add_argument(
        "--output", "-o", type=str, default=None, help="Output file path (default: print to stdout)"
    )

    args = parser.parse_args()

    if args.format == "typescript":
        exported_content = export_typescript_models()
    else:
        exported_content = export_schema(args.dialect)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(exported_content, encoding="utf-8")
        print(f"✅ {args.format.capitalize()} schema exported to {args.output}")
    else:
        print(exported_content)


if __name__ == "__main__":
    main()
