"""PDX-related entities - Implant, Measure, and Mouse."""

from datetime import date
from typing import TYPE_CHECKING, Optional, Union
from uuid import UUID, uuid4

from pydantic import computed_field
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .trial import PDXTrial


class Implant(SQLModel, table=True):
    """
    Implant entity - represents an implant generated by a PDX trial.
    
    Attributes:
        id: Unique identifier (UUID)
        implant_location: Location of the implant
        type: Type of implant
        type: Type of implant
        mouse_id: FK to Mouse
    """
    
    __tablename__ = "implant"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    implant_location: Optional[str] = Field(default=None, max_length=100)
    type: Optional[str] = Field(default=None, max_length=50)
    # Foreign keys (required - 1:N relationship with Mouse)
    mouse_id: UUID = Field(foreign_key="mouse.id", description="FK to Mouse")
    
    # Relationships
    mouse: Optional["Mouse"] = Relationship(back_populates="implants")
    measures: list["Measure"] = Relationship(back_populates="implant")


class Measure(SQLModel, table=True):
    """
    Measure entity - records size measurements for an implant over time.

    Tumor volume is determined by external caliper measurement. Two perpendicular
    dimensions are recorded: the major diameter (length) and the minor diameter
    (width). The tumor volume is estimated using the formula:

        Volume (mm³) = (Length × Width²) / 2

    All measurements are expressed in millimetres (mm) and the resulting volume
    in cubic millimetres (mm³).

    Attributes:
        id: Unique identifier (UUID)
        measure_date: Date of measurement
        length: Major diameter (longest dimension) in mm
        width: Minor diameter (perpendicular, shortest dimension) in mm
        tumor_volume: Computed tumor volume in mm³ (read-only, not stored)
        implant_id: FK to Implant
    """
    
    __tablename__ = "measure"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    measure_date: Union[date, None] = Field(default=None)
    length: Optional[float] = Field(default=None, description="Major diameter in mm")
    width: Optional[float] = Field(default=None, description="Minor diameter in mm")
    
    # Foreign keys (required - 1:N relationship with Implant)
    implant_id: UUID = Field(foreign_key="implant.id", description="FK to Implant")
    
    # Relationships
    implant: Optional["Implant"] = Relationship(back_populates="measures")

    @computed_field
    @property
    def tumor_volume(self) -> Optional[float]:
        """Tumor volume in mm³, computed as (Length × Width²) / 2."""
        if self.length is None or self.width is None:
            return None
        return (self.length * self.width ** 2) / 2


class Mouse(SQLModel, table=True):
    """
    Mouse entity - represents a mouse used in a PDX trial.
    
    Attributes:
        id: Unique identifier (UUID)
        birth_date: Date of birth
        death_cause: Cause of death
        animal_facility: Animal facility identifier
        proex: PROEX number
        strain: Mouse strain
        sex: Biological sex
        death_date: Date of death
        pdx_trial_id: FK to PDXTrial
    """
    
    __tablename__ = "mouse"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    birth_date: Union[date, None] = Field(default=None)
    death_cause: Optional[str] = Field(default=None, max_length=100)
    animal_facility: Optional[str] = Field(default=None, max_length=100)
    proex: Optional[str] = Field(default=None, max_length=50)
    strain: Optional[str] = Field(default=None, max_length=50)
    sex: Optional[str] = Field(default=None, max_length=20)
    death_date: Union[date, None] = Field(default=None)
    
    # Foreign keys (required - 1:1 relationship with PDXTrial)
    pdx_trial_id: str = Field(foreign_key="pdx_trial.id", description="FK to PDXTrial")
    
    # Relationships
    pdx_trial: Optional["PDXTrial"] = Relationship(back_populates="mouse")
    implants: list["Implant"] = Relationship(back_populates="mouse")
