import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  integer,
  date,
  real,
} from 'drizzle-orm/pg-core';

// ============================================
// MAIN ENTITIES
// ============================================

// Patient
export const patient = pgTable('patient', {
  nhc: varchar('nhc').primaryKey(), // Clinical History Number
  sex: varchar('sex'),
  birthDate: date('birth_date'),
});

// Tumor
export const tumor = pgTable('tumor', {
  biobankCode: varchar('biobank_code').primaryKey(),
  labCode: varchar('lab_code'),
  classification: varchar('classification'),
  apObservation: text('ap_observation'),
  grade: varchar('grade'),
  organ: varchar('organ'),
  status: varchar('status'),
  tnm: varchar('tnm'),
  // FK to Patient (Presents relationship 1:N)
  patientNhc: varchar('patient_nhc').notNull().references(() => patient.nhc),
  registrationDate: date('registration_date'),
  operationDate: date('operation_date'),
});

// LiquidBiopsy
export const liquidBiopsy = pgTable('liquid_biopsy', {
  id: uuid('id').primaryKey().defaultRandom(),
  hasSerum: boolean('has_serum'),
  hasBuffy: boolean('has_buffy'),
  hasPlasma: boolean('has_plasma'),
  // FK to Tumor (Presents relationship 0..1:1)
  tumorBiobankCode: varchar('tumor_biobank_code').references(() => tumor.biobankCode),
  biopsyDate: date('biopsy_date'),
});

// Biomodel
export const biomodel = pgTable('biomodel', {
  id: uuid('id').primaryKey().defaultRandom(),
  type: varchar('type'),
  preclinicalTrials: text('preclinical_trials'),
  description: text('description'),
  creationDate: date('creation_date'),
  status: varchar('status'),
  progresses: boolean('progresses'),
  viability: real('viability'),
  // FK to Tumor (Generates relationship 1:N)
  tumorBiobankCode: varchar('tumor_biobank_code').notNull().references(() => tumor.biobankCode),
});

// Passage
export const passage = pgTable('passage', {
  id: uuid('id').primaryKey().defaultRandom(),
  number: integer('number'),
  status: varchar('status'),
  sIndex: real('s_index'),
  viability: real('viability'),
  description: text('description'),
  // FK to Biomodel (Has relationship 1:0..2)
  biomodelId: uuid('biomodel_id').notNull().references(() => biomodel.id),
});

// ============================================
// TRIAL AND SUBTYPES (Is_a Inheritance)
// ============================================

// Trial (parent entity)
export const trial = pgTable('trial', {
  id: uuid('id').primaryKey().defaultRandom(),
  success: boolean('success'),
  description: text('description'),
  creationDate: date('creation_date'),
  biobankShipment: boolean('biobank_shipment'),
  biobankArrivalDate: date('biobank_arrival_date'),
  // FK to Passage (Has relationship 1:N)
  passageId: uuid('passage_id').notNull().references(() => passage.id),
});

// PDXTrial (Trial subtype)
export const pdxTrial = pgTable('pdx_trial', {
  id: uuid('id').primaryKey().references(() => trial.id),
  ffpe: boolean('ffpe'),
  heSlide: boolean('he_slide'),
  ihqData: text('ihq_data'),
  latencyWeeks: integer('latency_weeks'),
  sIndex: real('s_index'),
  scannerMagnification: varchar('scanner_magnification'),
});

// PDOTrial (Trial subtype)
export const pdoTrial = pgTable('pdo_trial', {
  id: uuid('id').primaryKey().references(() => trial.id),
  dropCount: integer('drop_count'),
  frozenOrganoidCount: integer('frozen_organoid_count'),
  organoidCount: integer('organoid_count'),
  plateType: varchar('plate_type'),
  visualizationDay: integer('visualization_day'),
  assessment: varchar('assessment'),
});

// LCTrial (Trial subtype)
export const lcTrial = pgTable('lc_trial', {
  id: uuid('id').primaryKey().references(() => trial.id),
  confluence: real('confluence'),
  spheroids: boolean('spheroids'),
  digestionDate: date('digestion_date'),
  cellLine: varchar('cell_line'),
  plateType: varchar('plate_type'),
});

// ============================================
// ENTITIES RELATED TO PDX TRIAL
// ============================================

// Implant (generated by PDXTrial)
export const implant = pgTable('implant', {
  id: uuid('id').primaryKey().defaultRandom(),
  implantLocation: varchar('implant_location'),
  type: varchar('type'),
  sizeLimit: real('size_limit'),
  // FK to PDXTrial (Generates relationship 1:N)
  pdxTrialId: uuid('pdx_trial_id').notNull().references(() => pdxTrial.id),
});

// SizeRecord (related to Implant)
export const sizeRecord = pgTable('size_record', {
  id: uuid('id').primaryKey().defaultRandom(),
  weekNumber: integer('week_number'),
  initialSizeMm3: real('initial_size_mm3'),
  finalSizeMm3: real('final_size_mm3'),
  // FK to Implant (Presents relationship 1:N)
  implantId: uuid('implant_id').notNull().references(() => implant.id),
});

// Mouse
export const mouse = pgTable('mouse', {
  id: uuid('id').primaryKey().defaultRandom(),
  birthDate: date('birth_date'),
  deathCause: varchar('death_cause'),
  animalFacility: varchar('animal_facility'),
  proex: varchar('proex'),
  strain: varchar('strain'),
  sex: varchar('sex'),
  deathDate: date('death_date'),
  // FK to PDXTrial (Associates relationship 1:1)
  pdxTrialId: uuid('pdx_trial_id').notNull().references(() => pdxTrial.id),
});

// ============================================
// ENTITIES RELATED TO LC TRIAL
// ============================================

// FACS
export const facs = pgTable('facs', {
  id: uuid('id').primaryKey().defaultRandom(),
  // FK to LCTrial (Has relationship 1:0..1)
  lcTrialId: uuid('lc_trial_id').references(() => lcTrial.id),
});

// ============================================
// ENTITIES RELATED TO TRIAL
// ============================================

// UsageRecord
export const usageRecord = pgTable('usage_record', {
  id: uuid('id').primaryKey().defaultRandom(),
  usageType: varchar('usage_type'),
  description: text('description'),
  date: date('date'),
  // FK to Trial (Presents relationship 1:0..N)
  trialId: uuid('trial_id').notNull().references(() => trial.id),
});

// Image
export const image = pgTable('image', {
  id: uuid('id').primaryKey().defaultRandom(),
  date: date('date'),
  type: varchar('type'),
  apReview: text('ap_review'),
  // FK to Trial (Generates relationship 1:0..N)
  trialId: uuid('trial_id').notNull().references(() => trial.id),
});

// Cryopreservation
export const cryopreservation = pgTable('cryopreservation', {
  id: uuid('id').primaryKey().defaultRandom(),
  location: varchar('location'),
  date: date('date'),
  vialCount: integer('vial_count'),
  // FK to Trial (Experiments relationship 1:0..N)
  trialId: uuid('trial_id').notNull().references(() => trial.id),
});

// GenomicSequencing
export const genomicSequencing = pgTable('genomic_sequencing', {
  id: uuid('id').primaryKey().defaultRandom(),
  // Parameters to be defined
  // FK to Trial (Associates relationship 1:0..1)
  trialId: uuid('trial_id').references(() => trial.id),
});

// MolecularData
export const molecularData = pgTable('molecular_data', {
  id: uuid('id').primaryKey().defaultRandom(),
  // FK to Trial (Associates relationship 1:0..1)
  trialId: uuid('trial_id').references(() => trial.id),
});
