"""PDX-related entities - Implant, SizeRecord, and Mouse."""

from datetime import date
from typing import TYPE_CHECKING, Optional, Union
from uuid import UUID, uuid4

from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .trial import PDXTrial


class Implant(SQLModel, table=True):
    """
    Implant entity - represents an implant generated by a PDX trial.
    
    Attributes:
        id: Unique identifier (UUID)
        implant_location: Location of the implant
        type: Type of implant
        size_limit: Size limit in mm³
        pdx_trial_id: FK to PDXTrial
    """
    
    __tablename__ = "implant"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    implant_location: Optional[str] = Field(default=None, max_length=100)
    type: Optional[str] = Field(default=None, max_length=50)
    size_limit: Optional[float] = Field(default=None)
    
    # Foreign keys (required - 1:N relationship with PDXTrial)
    pdx_trial_id: UUID = Field(foreign_key="pdx_trial.id", description="FK to PDXTrial")
    
    # Relationships
    pdx_trial: Optional["PDXTrial"] = Relationship(back_populates="implants")
    size_records: list["SizeRecord"] = Relationship(back_populates="implant")


class SizeRecord(SQLModel, table=True):
    """
    SizeRecord entity - records size measurements for an implant over time.
    
    Attributes:
        id: Unique identifier (UUID)
        week_number: Week number of the measurement
        initial_size_mm3: Initial size in mm³
        final_size_mm3: Final size in mm³
        implant_id: FK to Implant
    """
    
    __tablename__ = "size_record"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    week_number: Optional[int] = Field(default=None)
    initial_size_mm3: Optional[float] = Field(default=None)
    final_size_mm3: Optional[float] = Field(default=None)
    
    # Foreign keys (required - 1:N relationship with Implant)
    implant_id: UUID = Field(foreign_key="implant.id", description="FK to Implant")
    
    # Relationships
    implant: Optional["Implant"] = Relationship(back_populates="size_records")


class Mouse(SQLModel, table=True):
    """
    Mouse entity - represents a mouse used in a PDX trial.
    
    Attributes:
        id: Unique identifier (UUID)
        birth_date: Date of birth
        death_cause: Cause of death
        animal_facility: Animal facility identifier
        proex: PROEX number
        strain: Mouse strain
        sex: Biological sex
        death_date: Date of death
        pdx_trial_id: FK to PDXTrial
    """
    
    __tablename__ = "mouse"
    
    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    
    # Fields
    birth_date: Union[date, None] = Field(default=None)
    death_cause: Optional[str] = Field(default=None, max_length=100)
    animal_facility: Optional[str] = Field(default=None, max_length=100)
    proex: Optional[str] = Field(default=None, max_length=50)
    strain: Optional[str] = Field(default=None, max_length=50)
    sex: Optional[str] = Field(default=None, max_length=20)
    death_date: Union[date, None] = Field(default=None)
    
    # Foreign keys (required - 1:1 relationship with PDXTrial)
    pdx_trial_id: UUID = Field(foreign_key="pdx_trial.id", description="FK to PDXTrial")
    
    # Relationships
    pdx_trial: Optional["PDXTrial"] = Relationship(back_populates="mouse")
